/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterPanel.java
 *
 * Created on 2012-2-7, 14:01:21
 */
package pip;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import pip.Filter.BorderProcess;

/**
 *
 * @author Ovilia
 */
public class FilterPanel extends javax.swing.JPanel {

    private ImageProcessor imageProcessor;

    /** Creates new form FilterPanel */
    public FilterPanel(ImageProcessor imageProcessor) {
        this.imageProcessor = imageProcessor;
        initComponents();
        rightPanel.setLayout(new BorderLayout());

        // button listener
        robertButton.addActionListener(new ButtonListener());
        prewittButton.addActionListener(new ButtonListener());
        sobelButton.addActionListener(new ButtonListener());
        gaussianButton.addActionListener(new ButtonListener());
        medianButton.addActionListener(new ButtonListener());

        // add button to group
        filterButtonGroup.add(robertButton);
        filterButtonGroup.add(prewittButton);
        filterButtonGroup.add(sobelButton);
        filterButtonGroup.add(gaussianButton);
        filterButtonGroup.add(medianButton);
        
        borderButtonGroup.add(blackButton);
        borderButtonGroup.add(mirrorButton);
        borderButtonGroup.add(nearestButton);
        borderButtonGroup.add(periodicButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterButtonGroup = new javax.swing.ButtonGroup();
        borderButtonGroup = new javax.swing.ButtonGroup();
        leftPanel = new javax.swing.JPanel();
        radioPanel = new javax.swing.JPanel();
        robertButton = new javax.swing.JRadioButton();
        prewittButton = new javax.swing.JRadioButton();
        sobelButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        gaussianButton = new javax.swing.JRadioButton();
        medianButton = new javax.swing.JRadioButton();
        operatorLabel = new javax.swing.JLabel();
        filterLabel = new javax.swing.JLabel();
        radioLabel = new javax.swing.JLabel();
        radioText = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        blackButton = new javax.swing.JRadioButton();
        borderLabel = new javax.swing.JLabel();
        nearestButton = new javax.swing.JRadioButton();
        mirrorButton = new javax.swing.JRadioButton();
        periodicButton = new javax.swing.JRadioButton();
        rightPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        leftPanel.setName("leftPanel"); // NOI18N

        radioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pip.PIPApp.class).getContext().getResourceMap(FilterPanel.class);
        radioPanel.setToolTipText(resourceMap.getString("radioPanel.toolTipText")); // NOI18N
        radioPanel.setName("radioPanel"); // NOI18N

        robertButton.setSelected(true);
        robertButton.setText(resourceMap.getString("robertButton.text")); // NOI18N
        robertButton.setName("robertButton"); // NOI18N

        prewittButton.setText(resourceMap.getString("prewittButton.text")); // NOI18N
        prewittButton.setName("prewittButton"); // NOI18N

        sobelButton.setText(resourceMap.getString("sobelButton.text")); // NOI18N
        sobelButton.setName("sobelButton"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        gaussianButton.setText(resourceMap.getString("gaussianButton.text")); // NOI18N
        gaussianButton.setName("gaussianButton"); // NOI18N

        medianButton.setText(resourceMap.getString("medianButton.text")); // NOI18N
        medianButton.setName("medianButton"); // NOI18N

        operatorLabel.setFont(resourceMap.getFont("operatorLabel.font")); // NOI18N
        operatorLabel.setText(resourceMap.getString("operatorLabel.text")); // NOI18N
        operatorLabel.setName("operatorLabel"); // NOI18N

        filterLabel.setFont(resourceMap.getFont("filterLabel.font")); // NOI18N
        filterLabel.setText(resourceMap.getString("filterLabel.text")); // NOI18N
        filterLabel.setName("filterLabel"); // NOI18N

        radioLabel.setText(resourceMap.getString("radioLabel.text")); // NOI18N
        radioLabel.setName("radioLabel"); // NOI18N

        radioText.setText(resourceMap.getString("radioText.text")); // NOI18N
        radioText.setEnabled(false);
        radioText.setName("radioText"); // NOI18N
        radioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                radioTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout radioPanelLayout = new javax.swing.GroupLayout(radioPanel);
        radioPanel.setLayout(radioPanelLayout);
        radioPanelLayout.setHorizontalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(gaussianButton))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(robertButton))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sobelButton))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(operatorLabel))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(filterLabel))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medianButton)
                            .addGroup(radioPanelLayout.createSequentialGroup()
                                .addComponent(radioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(prewittButton)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        radioPanelLayout.setVerticalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operatorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(robertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prewittButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobelButton)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gaussianButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medianButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    .addComponent(radioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pip.PIPApp.class).getContext().getActionMap(FilterPanel.class, this);
        applyButton.setAction(actionMap.get("filter")); // NOI18N
        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N

        blackButton.setText(resourceMap.getString("blackButton.text")); // NOI18N
        blackButton.setToolTipText(resourceMap.getString("blackButton.toolTipText")); // NOI18N
        blackButton.setName("blackButton"); // NOI18N

        borderLabel.setFont(resourceMap.getFont("borderLabel.font")); // NOI18N
        borderLabel.setText(resourceMap.getString("borderLabel.text")); // NOI18N
        borderLabel.setToolTipText(resourceMap.getString("borderLabel.toolTipText")); // NOI18N
        borderLabel.setName("borderLabel"); // NOI18N

        nearestButton.setSelected(true);
        nearestButton.setText(resourceMap.getString("nearestButton.text")); // NOI18N
        nearestButton.setToolTipText(resourceMap.getString("nearestButton.toolTipText")); // NOI18N
        nearestButton.setName("nearestButton"); // NOI18N

        mirrorButton.setText(resourceMap.getString("mirrorButton.text")); // NOI18N
        mirrorButton.setToolTipText(resourceMap.getString("mirrorButton.toolTipText")); // NOI18N
        mirrorButton.setName("mirrorButton"); // NOI18N

        periodicButton.setText(resourceMap.getString("periodicButton.text")); // NOI18N
        periodicButton.setToolTipText(resourceMap.getString("periodicButton.toolTipText")); // NOI18N
        periodicButton.setName("periodicButton"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borderLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blackButton)
                            .addComponent(nearestButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(periodicButton)
                            .addComponent(mirrorButton))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(blackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nearestButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mirrorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodicButton)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(applyButton)
                .addContainerGap())
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(radioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(radioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        rightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rightPanel.setName("rightPanel"); // NOI18N

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void radioTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioTextKeyReleased
    String text = radioText.getText();
    try {
        int value = Integer.parseInt(text);
        if (value < 1) {
            radioText.setText("1");
        }
    } catch (NumberFormatException e) {
        radioText.setText("1");
    }
}//GEN-LAST:event_radioTextKeyReleased

    @Action
    public Task filter() {
        return new FilterTask(org.jdesktop.application.Application.getInstance(pip.PIPApp.class));
    }

    private class FilterTask extends org.jdesktop.application.Task<Object, Void> {

        FilterTask(org.jdesktop.application.Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            BufferedImage image = null;
            BorderProcess borderProcess = null;
            
            // set borderProcess 
            if (blackButton.isSelected()) {
                borderProcess = BorderProcess.BLACK;
            } else if (mirrorButton.isSelected()) {
                borderProcess = BorderProcess.MIRROR;
            } else if (nearestButton.isSelected()) {
                borderProcess = BorderProcess.NEAREST;
            } else {
                borderProcess = BorderProcess.PERIODIC;
            }
            
            // set filter
            if (robertButton.isSelected()) {
                RobertFilter filter = new RobertFilter(
                        imageProcessor.getBufferedImage(), borderProcess);
                image = filter.getFilteredImage();
            }

            // show out come image
            if (image != null) {
                imagePanel = new ImagePanel(image);
                imagePanel.setMaxSize(rightPanel.getSize().width,
                        rightPanel.getSize().height);
                rightPanel.removeAll();
                rightPanel.add(imagePanel);
            }
            return null;
        }

        @Override
        protected void succeeded(Object result) {
        }
    }

    private class ButtonListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            if (medianButton.isSelected() || gaussianButton.isSelected()) {
                radioText.setEnabled(true);
            } else {
                radioText.setEnabled(false);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JRadioButton blackButton;
    private javax.swing.ButtonGroup borderButtonGroup;
    private javax.swing.JLabel borderLabel;
    private javax.swing.ButtonGroup filterButtonGroup;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JRadioButton gaussianButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JRadioButton medianButton;
    private javax.swing.JRadioButton mirrorButton;
    private javax.swing.JRadioButton nearestButton;
    private javax.swing.JLabel operatorLabel;
    private javax.swing.JRadioButton periodicButton;
    private javax.swing.JRadioButton prewittButton;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JPanel radioPanel;
    private javax.swing.JTextField radioText;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JRadioButton robertButton;
    private javax.swing.JRadioButton sobelButton;
    // End of variables declaration//GEN-END:variables
    private ImagePanel imagePanel;
}
