/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterPanel.java
 *
 * Created on 2012-2-7, 14:01:21
 */
package pip;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import pip.Filter.BorderProcess;

/**
 *
 * @author Ovilia
 */
public class FilterPanel extends javax.swing.JPanel {

    private ImageProcessor imageProcessor;

    /** Creates new form FilterPanel */
    public FilterPanel(ImageProcessor imageProcessor) {
        this.imageProcessor = imageProcessor;
        initComponents();
        rightPanel.setLayout(new BorderLayout());

        // button listener
        robertButton.addActionListener(new ButtonListener());
        prewittButton.addActionListener(new ButtonListener());
        sobelButton.addActionListener(new ButtonListener());
        gaussianButton.addActionListener(new ButtonListener());
        medianButton.addActionListener(new ButtonListener());

        // add button to group
        filterButtonGroup.add(robertButton);
        filterButtonGroup.add(prewittButton);
        filterButtonGroup.add(sobelButton);
        filterButtonGroup.add(gaussianButton);
        filterButtonGroup.add(medianButton);
        
        borderButtonGroup.add(blackButton);
        borderButtonGroup.add(mirrorButton);
        borderButtonGroup.add(nearestButton);
        borderButtonGroup.add(periodicButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterButtonGroup = new javax.swing.ButtonGroup();
        borderButtonGroup = new javax.swing.ButtonGroup();
        leftPanel = new javax.swing.JPanel();
        radioPanel = new javax.swing.JPanel();
        robertButton = new javax.swing.JRadioButton();
        prewittButton = new javax.swing.JRadioButton();
        sobelButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        gaussianButton = new javax.swing.JRadioButton();
        medianButton = new javax.swing.JRadioButton();
        operatorLabel = new javax.swing.JLabel();
        filterLabel = new javax.swing.JLabel();
        radioLabel = new javax.swing.JLabel();
        radioText = new javax.swing.JTextField();
        sigmaLabel = new javax.swing.JLabel();
        sigmaSlider = new javax.swing.JSlider();
        applyButton = new javax.swing.JButton();
        leftDownPanel = new javax.swing.JPanel();
        blackButton = new javax.swing.JRadioButton();
        borderLabel = new javax.swing.JLabel();
        nearestButton = new javax.swing.JRadioButton();
        mirrorButton = new javax.swing.JRadioButton();
        periodicButton = new javax.swing.JRadioButton();
        rightPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        leftPanel.setName("leftPanel"); // NOI18N

        radioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pip.PIPApp.class).getContext().getResourceMap(FilterPanel.class);
        radioPanel.setToolTipText(resourceMap.getString("radioPanel.toolTipText")); // NOI18N
        radioPanel.setName("radioPanel"); // NOI18N

        robertButton.setSelected(true);
        robertButton.setText(resourceMap.getString("robertButton.text")); // NOI18N
        robertButton.setName("robertButton"); // NOI18N

        prewittButton.setText(resourceMap.getString("prewittButton.text")); // NOI18N
        prewittButton.setName("prewittButton"); // NOI18N

        sobelButton.setText(resourceMap.getString("sobelButton.text")); // NOI18N
        sobelButton.setName("sobelButton"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        gaussianButton.setText(resourceMap.getString("gaussianButton.text")); // NOI18N
        gaussianButton.setName("gaussianButton"); // NOI18N

        medianButton.setText(resourceMap.getString("medianButton.text")); // NOI18N
        medianButton.setName("medianButton"); // NOI18N

        operatorLabel.setFont(resourceMap.getFont("operatorLabel.font")); // NOI18N
        operatorLabel.setText(resourceMap.getString("operatorLabel.text")); // NOI18N
        operatorLabel.setName("operatorLabel"); // NOI18N

        filterLabel.setFont(resourceMap.getFont("filterLabel.font")); // NOI18N
        filterLabel.setText(resourceMap.getString("filterLabel.text")); // NOI18N
        filterLabel.setName("filterLabel"); // NOI18N

        radioLabel.setText(resourceMap.getString("radioLabel.text")); // NOI18N
        radioLabel.setName("radioLabel"); // NOI18N

        radioText.setText(resourceMap.getString("radioText.text")); // NOI18N
        radioText.setEnabled(false);
        radioText.setName("radioText"); // NOI18N
        radioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                radioTextKeyReleased(evt);
            }
        });

        sigmaLabel.setText(resourceMap.getString("sigmaLabel.text")); // NOI18N
        sigmaLabel.setName("sigmaLabel"); // NOI18N

        sigmaSlider.setMaximum(1000);
        sigmaSlider.setValue(60);
        sigmaSlider.setEnabled(false);
        sigmaSlider.setName("sigmaSlider"); // NOI18N
        sigmaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sigmaSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout radioPanelLayout = new javax.swing.GroupLayout(radioPanel);
        radioPanel.setLayout(radioPanelLayout);
        radioPanelLayout.setHorizontalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(robertButton))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sobelButton))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(operatorLabel))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(prewittButton))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterLabel)
                            .addComponent(gaussianButton)
                            .addGroup(radioPanelLayout.createSequentialGroup()
                                .addComponent(radioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(medianButton)
                            .addGroup(radioPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sigmaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sigmaLabel))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        radioPanelLayout.setVerticalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operatorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(robertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prewittButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLabel)
                    .addComponent(radioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaussianButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sigmaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sigmaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medianButton)
                .addContainerGap())
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pip.PIPApp.class).getContext().getActionMap(FilterPanel.class, this);
        applyButton.setAction(actionMap.get("filter")); // NOI18N
        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N

        leftDownPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        leftDownPanel.setName("leftDownPanel"); // NOI18N

        blackButton.setText(resourceMap.getString("blackButton.text")); // NOI18N
        blackButton.setToolTipText(resourceMap.getString("blackButton.toolTipText")); // NOI18N
        blackButton.setName("blackButton"); // NOI18N

        borderLabel.setFont(resourceMap.getFont("borderLabel.font")); // NOI18N
        borderLabel.setText(resourceMap.getString("borderLabel.text")); // NOI18N
        borderLabel.setToolTipText(resourceMap.getString("borderLabel.toolTipText")); // NOI18N
        borderLabel.setName("borderLabel"); // NOI18N

        nearestButton.setSelected(true);
        nearestButton.setText(resourceMap.getString("nearestButton.text")); // NOI18N
        nearestButton.setToolTipText(resourceMap.getString("nearestButton.toolTipText")); // NOI18N
        nearestButton.setName("nearestButton"); // NOI18N

        mirrorButton.setText(resourceMap.getString("mirrorButton.text")); // NOI18N
        mirrorButton.setToolTipText(resourceMap.getString("mirrorButton.toolTipText")); // NOI18N
        mirrorButton.setName("mirrorButton"); // NOI18N

        periodicButton.setText(resourceMap.getString("periodicButton.text")); // NOI18N
        periodicButton.setToolTipText(resourceMap.getString("periodicButton.toolTipText")); // NOI18N
        periodicButton.setName("periodicButton"); // NOI18N

        javax.swing.GroupLayout leftDownPanelLayout = new javax.swing.GroupLayout(leftDownPanel);
        leftDownPanel.setLayout(leftDownPanelLayout);
        leftDownPanelLayout.setHorizontalGroup(
            leftDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftDownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borderLabel)
                    .addGroup(leftDownPanelLayout.createSequentialGroup()
                        .addGroup(leftDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blackButton)
                            .addComponent(nearestButton))
                        .addGap(18, 18, 18)
                        .addGroup(leftDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(periodicButton)
                            .addComponent(mirrorButton))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        leftDownPanelLayout.setVerticalGroup(
            leftDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftDownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftDownPanelLayout.createSequentialGroup()
                        .addComponent(blackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nearestButton))
                    .addGroup(leftDownPanelLayout.createSequentialGroup()
                        .addComponent(mirrorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodicButton)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leftDownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applyButton))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addComponent(radioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leftDownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyButton)
                .addGap(36, 36, 36))
        );

        rightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rightPanel.setName("rightPanel"); // NOI18N

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void radioTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioTextKeyReleased
    String text = radioText.getText();
    try {
        int value = Integer.parseInt(text);
        if (value < 1) {
            radioText.setText("1");
        }
    } catch (NumberFormatException e) {
        radioText.setText("1");
    }
}//GEN-LAST:event_radioTextKeyReleased

private void sigmaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sigmaSliderStateChanged
    sigmaLabel.setText("Sigma: " + (sigmaSlider.getValue() / 100) + "."
            + (sigmaSlider.getValue() % 100));
}//GEN-LAST:event_sigmaSliderStateChanged

    @Action
    public Task filter() {
        return new FilterTask(org.jdesktop.application.Application.getInstance(pip.PIPApp.class));
    }

    private class FilterTask extends org.jdesktop.application.Task<Object, Void> {

        FilterTask(org.jdesktop.application.Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            BufferedImage image = null;
            BorderProcess borderProcess = null;
            
            // set borderProcess 
            if (blackButton.isSelected()) {
                borderProcess = BorderProcess.BLACK;
            } else if (mirrorButton.isSelected()) {
                borderProcess = BorderProcess.MIRROR;
            } else if (nearestButton.isSelected()) {
                borderProcess = BorderProcess.NEAREST;
            } else {
                borderProcess = BorderProcess.PERIODIC;
            }
            
            // set filter
            if (robertButton.isSelected()) {
                RobertFilter filter = new RobertFilter(
                        imageProcessor.getGrayScaleImage(null), borderProcess);
                image = filter.getFilteredImage();
            } else if (prewittButton.isSelected()) {
                PrewittFilter filter = new PrewittFilter(
                        imageProcessor.getGrayScaleImage(null), borderProcess);
                image = filter.getFilteredImage();
            } else if (sobelButton.isSelected()) {
                SobelFilter filter = new SobelFilter(
                        imageProcessor.getGrayScaleImage(null), borderProcess);
                image = filter.getFilteredImage();
            } else if (gaussianButton.isSelected()) {
                GaussianFilter filter = new GaussianFilter(
                        imageProcessor.getGrayScaleImage(null), 
                        Integer.parseInt(radioText.getText()),
                        getSigma(),
                        borderProcess);
                image = filter.getFilteredImage();
                
            } else if (medianButton.isSelected()) {
                MedianFilter filter = new MedianFilter(
                        imageProcessor.getGrayScaleImage(null), 
                        Integer.parseInt(radioText.getText()),
                        borderProcess);
                image = filter.getFilteredImage();
            }

            // show out come image
            if (image != null) {
                imagePanel = new ImagePanel(image);
                imagePanel.setMaxSize(rightPanel.getSize().width - 20,
                        rightPanel.getSize().height - 20);
                rightPanel.removeAll();
                rightPanel.add(imagePanel);
            }
            return null;
        }

        @Override
        protected void succeeded(Object result) {
        }
    }

    private class ButtonListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            if (medianButton.isSelected()) {
                radioText.setEnabled(true);
                sigmaSlider.setEnabled(false);
            } else if (gaussianButton.isSelected()) {
                sigmaSlider.setEnabled(true);
                radioText.setEnabled(true);
            } else {
                radioText.setEnabled(false);
                sigmaSlider.setEnabled(false);
            }
        }
    }
    
    private double getSigma() {
        return sigmaSlider.getValue() / 100.0;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JRadioButton blackButton;
    private javax.swing.ButtonGroup borderButtonGroup;
    private javax.swing.JLabel borderLabel;
    private javax.swing.ButtonGroup filterButtonGroup;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JRadioButton gaussianButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftDownPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JRadioButton medianButton;
    private javax.swing.JRadioButton mirrorButton;
    private javax.swing.JRadioButton nearestButton;
    private javax.swing.JLabel operatorLabel;
    private javax.swing.JRadioButton periodicButton;
    private javax.swing.JRadioButton prewittButton;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JPanel radioPanel;
    private javax.swing.JTextField radioText;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JRadioButton robertButton;
    private javax.swing.JLabel sigmaLabel;
    private javax.swing.JSlider sigmaSlider;
    private javax.swing.JRadioButton sobelButton;
    // End of variables declaration//GEN-END:variables
    private ImagePanel imagePanel;
}
